### ISSUE TITLE
Route `/questions` returns status code 500

### ISSUE THREAD

**Issue by vrackovic** [execom-eu/OOP-Test-Generator#119]
- Route `/questions` returns status code 500

**Comment by iscekic** [comment]
Please provide more detailed info in bug reports.

**Comment by vrackovic** [comment]
When hitting `localhost:8080/api/questions` as logged in user response is `500 Internal Server Error`

**Comment by vrackovic** [comment]
Problem caused by invalid data entered directly in DB.
