### ISSUE TITLE
Write unit and integration tests for Login Controller

### ISSUE THREAD

**Issue by sugrinov** [execom-eu/OOP-Test-Generator#159]

**Comment by dujfalusi** [comment]
After investigation, I suggest using `PowerMock` or moving controller static methods to `@PostConstruct`.
( `AuthenticationUtil.verifyGoogleToken(accessToken)` and `AuthenticationUtil.getUser()` )

In the case of removing static mocking `GoogleIdToken` could be something like this:
```
    Header header = new Header();
    header.setAlgorithm("RS25");
    Payload payload = newPayload(CLIENT_ID);
    GoogleIdToken idToken = new GoogleIdToken(header, payload, new byte[0], new byte[0]);

```
Note: `accessToken` is actually unverified `googleIdToken` as String.

**Comment by Fistulator** [comment]
Wrote some unit tests for this class, will proceed with integration tests.
