### ISSUE TITLE
Fix content displaying depending on user role

### ISSUE THREAD

**Issue by vrackovic** [execom-eu/OOP-Test-Generator#173]
- Check which content will be displayed depending on user roles.
- Roles are: 
     - Admin
     - Reviewer
     - Applicant
     - Employee

**Comment by Fistulator** [comment]
I think this is working as intended, except if I misunderstood something.

**Comment by draganakovacevic** [comment]
Applicant: has a form in which applicant completes the data and then receives a test page. After completing the test, it returns to the home page of the application.

Admin: After logging in, he has a dashboard page showing the tests done with a spreadsheet about them (he can assign a reviewer, have him review and delete himself) as well as a section for invite employee and search tests. Also the options it has on the left are a category: where it can create a new category or search for an existing one, question: it can also create a new category or filter questions based on the category. The rest is part of the formula: in which it can create a new formula or search for existing ones. After logout returns to the home page of the application.

Employee: has all the options as an admin, only the dashboard page does not show tests.

Reviewer: it's actually an employee, it has all the capabilities of an employee. In case the admin in the table assigned an employee an obligation to review the test he became a reviewer. Now on the dashboard there are tests we have been given for review, but without the option to delete the test. We may review or assign someone else as a reviewer in case of busyness.
