### ISSUE TITLE
Dashboard Max points is always 0

### ISSUE THREAD

**Issue by vrackovic** [execom-eu/OOP-Test-Generator#181]
Fetching request to `/dashboard` responds with object that has wrong values for `maxPoints` and `awardedPoints` (always equals `0`)

**Comment by millevlada** [comment]
First we fix max points -> that comes from test questions.
Awarded points are part of review, that feature is still not implemented.
Therefore I'll split this into 2 issues, this one remains for max points only.

**Comment by millevlada** [comment]
Implemented as finishing review functionality
