### ISSUE TITLE
Implement functionality for assigning reviewer to test on Dashboard

### ISSUE THREAD

**Issue by sugrinov** [execom-eu/OOP-Test-Generator#196]
When clicking `Edit` button on a test in Dashboard we should be given an option to assign a reviewer to that test

**Comment by vrackovic** [comment]
Layout and mock done in #226

**Comment by millevlada** [comment]
actually, reviewers are assigned by doing 'assign reviewer...' action (first icon), and that is implemented with fx #278 . It is not clear what 'edit test' icon should do?

**Comment by millevlada** [comment]
Ok, I presume that 'edit test' is actually 'do review'... This would be done with other user story - #290, so I'll close this one.
