### ISSUE TITLE
Test fetching questions that are not active

### ISSUE THREAD

**Issue by vrackovic** [execom-eu/OOP-Test-Generator#230]
- After successful login as applicant, new test is generated with formula (e.g. `Java Test`)
- Later, question is modified so that it isn't active any more
- Using same formula as in first step, and generating new test for new user, test is somehow able to load question that has `active: false`

**Comment by mlcvijetinovic** [comment]
Analyzed reported bug and investigated flow how question is created, updated and deleted. Found that question cannot be visible in test, because if question is changed, its marked  as deleted and we filter out all question which are deleted. So this issue can be closed.
