### ISSUE TITLE
Question module issues

### ISSUE THREAD

**Issue by millevlada** [execom-eu/OOP-Test-Generator#302]
1. Selecting existing multiple choice questions does not `remember` what answers are correct.
2. Description of question should allow multiple lines inputs, preferably with some basic formattings (to be able to specify some parts of question as code blocks). This should also be properly rendered later when taking the test and doing the review.
3. Saving question would each time result in replicating the question model and making non active copies. Maybe that should be prevent with some explicit checks if any changes were done at all.
4. Once selected, Question filter can not be emptied.
5. It is not clear what `isActive` represents inside both Question and Answer? It seems it is really not needed in Answer at least, since with any change we deep copy entire question, with setting `deleted` to old question and all it's answers, while keeping `isActive=true` on them. Maybe temporarily disabling Question might have sense, then `isActive` might be keep for it, but UI does not support such option for  now.

**Comment by millevlada** [comment]
1 and 3 are fixed with #309.

**Comment by Fistulator** [comment]
4 is solved in #392
