### ISSUE TITLE
Fix sonar reported issues

### ISSUE THREAD

**Issue by millevlada** [execom-eu/OOP-Test-Generator#321]
Currently, local instance of sonar is configured on developer workstation.
It shows 4 bugs and 41 code smell, with default rule set of 'sonar way'.
It also does not have code coverage configured out of the box.

This issues can be fixed.

However it is planed to set up real 'test' instance of project on dedicated server, including proper devops infrastructure including jenkins builds that would include sonar goal, that would run as nightly scheduled job. That is part of #93.

**Comment by millevlada** [comment]
Just found out that there were previous efforts to establish some devops infra earlier. Sonar job was already existing, now it is just tweaked to get proper build in multimodule setup.
Results of sonar analyses are available at this link:
http://sonarqube.execom.co.yu:9000/dashboard?id=eu.execom.testgenerator%3Atest-generator

It is currently attached to develop branch by default, and it can be parametrized.

**Comment by dujfalusi** [comment]
this is done
