### ISSUE TITLE
Managing users

### ISSUE THREAD

**Issue by vrackovic** [execom-eu/OOP-Test-Generator#346]
Problems: 
- Current implementation doesn't allow users to be assigned role of `reviewer`, so reviewers can't be assigned to solved user tests

Todo: 
- User management screen and api should be supported
- Only users with role `admin` should see and use this screen
- Screen should be used to change existing user roles (`admin`, `user` and `reviewer`)

**Comment by dujfalusi** [comment]
At the moment assigning `REVIEWER` role to a user (EMPLOYEE or ADMINISTRATOR) is possible with assigning test review by an administrator.
I agree that will be great if the admin has user management screen. 
Also at the moment doesn't exist a way to delete a user.

**Comment by draganakovacevic** [comment]
This is currently working. Check what the issue was about @vrackovic
