### ISSUE TITLE
Fix timer restarting after refresh

### ISSUE THREAD

**Issue by vrackovic** [execom-eu/OOP-Test-Generator#354]
To recreate:
- Log in as guest
- After loaded test, look at timer on right side.
- Reload page, timer will get back to initial time

Issue:
- Backend is not counting time, and returns remaining time set on beginning of test
- Remaining Time is updated only after user has submitted `remainingTime` property while updating answers. 

Task:
- Current implementation doesn't stop user to enter and submit any value for `currentTime`. 
- Remaining time should be stored as Unix time, and checked before submitted. 
- Frontend should only be allowed to display remaining time, and current implementation allows it to change it and submit it

**Comment by Fistulator** [comment]
Fixed in pull request #385
