### ISSUE TITLE
Implement answers on new test after reload

### ISSUE THREAD

**Issue by vrackovic** [execom-eu/OOP-Test-Generator#360]
Flow:
- Guest user signs in, new test is generated, and displayed so that user can answer questions
- If user tries to reload page, same test will be loaded. Same applies for back button, and changing url by hand. No matter what, user will be redirected to generated test until test is submitted.
- Every time user answers a question (`onClick` for checkboxes, and `onBlur` for input field questions), answer is sant to BE with PUT method.

Problem: 
- Reloading page gets us test and questions fetched and displayed, but answers are not displayed.

Task:
- After test is reloaded, and test with questions is fetched, fetch answers for that `testId` for that user, and display saved questions.

Notes: 
- `/test/{testId}` doesn't return answers object. It should be fixed on backend so that previously answered questions are returned together with answers, so that answers can be mapped and rendered properly.

**Comment by dujfalusi** [comment]
Backend is updated with this pull request #379.

**Comment by Fistulator** [comment]
Solved in pull request #389
