### ISSUE TITLE
Missing "Cancel" button

### ISSUE THREAD

**Issue by dujfalusi** [execom-eu/OOP-Test-Generator#369]
![image](https://user-images.githubusercontent.com/19993915/58959439-6a0b7480-87a5-11e9-8d66-7babaf5a3cde.png)

The only way to cancel test review is to hit "X" in the top right corner. 
Maybe should be there "Cancel" button or clicking somewhere around modal.

**Comment by Fistulator** [comment]
Fixed in pull request #392
