### ISSUE TITLE
Create integration tests for user management

### ISSUE THREAD

**Issue by stanislavgrujic** [execom-eu/OOP-Test-Generator#37]
Use SpringContextRunner class

**Comment by dujfalusi** [comment]
@stanislavgrujic  What is the requirement of this issue? Already exist `UserControllerIntegrationTest` (that is actually JUnit test with mock data, testing the only API on the controller level)

**Comment by stanislavgrujic** [comment]
As far as I see, the task is moved to Done. It should be closed.
