### ISSUE TITLE
In the field "Points" on the "Question" screen, it is possible to enter negative numbers and special characters.

### ISSUE THREAD

**Issue by VojislavKovacevic** [execom-eu/OOP-Test-Generator#399]
In the field "Points" on the "Question" screen, it is possible to enter negative numbers and special characters.

The field should be limited to accept positive numbers only.

PO: Are decimal values requiered? 

![formula add recipe2020-04-02 12_04_25-Execom test](https://user-images.githubusercontent.com/63228397/78540387-621cc680-77f4-11ea-8afb-bd3ac08de26b.png)

**Comment by draganakovacevic** [comment]
Special characters for points in Question should not be possible to enter because field was numeric type. Screenshot for this bug is not correct because this is connected with Question not Formula form.
