### ISSUE TITLE
Elements overlapping on the review screen 

### ISSUE THREAD

**Issue by VojislavKovacevic** [execom-eu/OOP-Test-Generator#419]
Elements overlapping on the review screen. For question type "coding challenge", the dropdown menu is not fully visible.

![elementsIn reviewe2020-04-22 11_40_25-Execom test](https://user-images.githubusercontent.com/63228397/79978605-79201180-84a0-11ea-99ff-9388c267ad0d.png)

**Comment by VojislavKovacevic** [comment]
Issue still present. Develop branch 15.6.2020.

![test overlaping2020-06-15 11_16_59-Execom test](https://user-images.githubusercontent.com/63228397/84640906-9d292d80-aefa-11ea-9a87-dbe41b0a1683.png)

**Comment by adamovivan** [comment]
Please check it again, it should work. There is another problem: 
![Screenshot from 2020-06-23 15-34-03](https://user-images.githubusercontent.com/29520040/85410277-2d085080-b567-11ea-8179-77ce04a43c7b.png)
