### ISSUE TITLE
Code cleanup for ResponseEntities and endpoint names

### ISSUE THREAD

**Issue by adamovivan** [execom-eu/OOP-Test-Generator#429]
- Add ReponseEntity type in Controllers and GlobalExceptionHandler
- Refactor endpoint names like this: 
api/tests/submit -> /api/tests/actions/submit 
api/tests/update-answers -> /api/tests/actions/update
api/tests/assign-reviewer -> /api/tests/actions/assign

**Comment by VojislavKovacevic** [comment]
@draganakovacevic @stanislavgrujic @adamovivan 

How this can be tested from a user perspective?
Which functionalities are affected?
Is fix merged to a develop branch?
