### ISSUE TITLE
It is possible to create multiple choice questions without any answer offered.

### ISSUE THREAD

**Issue by VojislavKovacevic** [execom-eu/OOP-Test-Generator#438]
It is possible to create multiple choice questions without any answers offered.

scenario:
create question 
choose type "multiple choice"
**do not** add answers
save question

**Comment by adamovivan** [comment]
This was done intentionally so that the question could be updated later. Multiple choice question without any answer is an invalid question and should not be shown. This is fixed in pull request https://github.com/execom-eu/OOP-Test-Generator/pull/434.
