### ISSUE TITLE
Update response classes in CategoryController

### ISSUE THREAD

**Issue by stanislavgrujic** [execom-eu/OOP-Test-Generator#84]
Instead of CategoryResponse introduce new classes where each of the created classes will correspond to the given request class (e.g., on `CreateCategoryRequest` the system should return `CreateCategoryResponse`). 
Update the response classes on the following endpoints:
- createNewCategory
- getAllCategories (*fix spelling error in method name)
- updateCategory
- deleteCategory (just parametrize ResponseEntity with <Void>)

**Comment by dujfalusi** [comment]
This is done
