### ISSUE TITLE
Incorrect implementation of multiple choice answer validation

### ISSUE THREAD

**Issue by Varadski** [execom-eu/OOP-Test-Generator#88]
`public List<Answer> getSelectedAnswers() {
    return testQuestionAnswers.stream()
                              .filter(testQuestionAnswer -> testQuestionAnswer.isSelected())
                              .map(TestQuestionAnswer::getAnswer)
                              .collect(Collectors.toList());
  }`

The above will filter out the `TestQuestionAnswers` which were not selected, but it does not check if the selected answers are correct.

`public boolean isCorrectlyAnswered() {
    return getSelectedAnswers().stream().map(Answer::isCorrect).count() == question.getNumberOfCorrectAnswers();
  }`

This will count the number of selected answers that were provided by `getSelectedAnswers()` that were correct and if the numbers match it will return `true` and it will ignore all other answers which were provided (incorrect answers); it doesn't care how many answers were selected, or if incorrect answers were selected, as long as the number of correct answers selected is equal to the expected number of correct answers.

**Comment by millevlada** [comment]
seems this is long ago merged
