### ISSUE TITLE
Setup CI/CD with SonarQube static analasys for the project

### ISSUE THREAD

**Issue by stanislavgrujic** [execom-eu/OOP-Test-Generator#93]
The whole team should be present when this is done. Reach out to vilic@execom.eu to support you in the process. Should take around 1hr.

**Comment by millevlada** [comment]
Sonar goal is connected with Jenkins build job that is now available at:

https://jenkinsmaster.execom.eu/job/Execom-TestGenerator/

_Build-TestGenerator-Linux_ : Build job, used to check build status and also to generate Sonar statistics - project quality overview is available at:

http://sonarqube.execom.co.yu:9000/dashboard?id=eu.execom.testgenerator%3Atest-generator
